name: "Smart Traffic Analyzer"

on: [push]
jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up Smart Traffic Analyzer
          uses: actions/setup-node@v3